version: "3.8"

services:
  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  web-server-a:
    build: ./web-server-a
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
      - queue
    env_file:
      - ./web-server-a/.env

  web-server-b:
    build: ./web-server-b
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
      - queue
      - web-server-a
    env_file:
      - ./web-server-b/.env

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"

  redis:
    image: redis

  mongodb:
    image: mongo
