version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña
      MYSQL_DATABASE: webserva
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
